[package]
name = "auto_accessor"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.24"
quote = "0.6.10"
syn = {version = "0.15", features = ["extra-traits"]}
